### ISSUE TITLE
feature request: movable toast popup

### ISSUE THREAD

**Issue by mafima** [GryllsAddons/HCDeaths#1]
hello, HUGE thanks for coding this amazing addon!!!
would like to have toast/death popup less gameplay blocking, since in the middle of the screen it is too blocking.
i forked the repo and added the option for moving the toast/death popup. that might be a good starting point for you. it worked moving it on startup, but toggle does not seem to be working.

https://github.com/mafima/HCDeathsPlus
rename the folder to HCDeaths.

![image](https://github.com/GryllsAddons/HCDeaths/assets/3407209/e16e44f8-b717-440a-8828-429fa2d95049)

**Comment by GryllsAddons** [comment]
Thank you! I've added the ability to move and scale the toast and logs. You may need to do a `/hcd reset` if you have an error when updating the addon :)
