### ISSUE TITLE
Issue with addon

### ISSUE THREAD

**Issue by Mstuholla** [GryllsAddons/HCDeaths#3]
Addon completely stops working anytime a hardcore player dies in PvP. You must logout and back in to fix this issue.

**Comment by GryllsAddons** [comment]
Thanks, hopefully the latest update will fix this. Please let me know if you encounter any issues.

**Comment by Mstuholla** [comment]
Seems to have improved the situation. In the 2 days I've been using the new update, the addon only stopped working one time when a hardcore player died from natural causes.

**Comment by GryllsAddons** [comment]
Thanks, I will revisit this when the hardcore system messages are fixed in Turtle WoW as it may be an issue with how the natural causes message is formatted.

**Comment by GryllsAddons** [comment]
A timeout checker has been added to the latest version which should allow the addon to reset the current query if any problems were encountered when using /who. I haven't encountered the addon stopping working completely lately during limited testing but will keep this issue open for now.
