### ISSUE TITLE
Black font is unreadable

### ISSUE THREAD

**Issue by jendryk** [GryllsAddons/HCDeaths#4]
![obraz](https://github.com/GryllsAddons/HCDeaths/assets/7814954/8aaddfc1-9a94-4b53-b36b-c70e7d38da60)
I have this issue with log, sometimes it works perfectly (white font) and sometimes it looks like this.

**Comment by GryllsAddons** [comment]
Thanks, the text should be the default yellow color. Does this happen with any other tooltips or just with the log? are you using any other tooltip addons apart from the built in pfUI tooltip?

![image](https://github.com/GryllsAddons/HCDeaths/assets/107083057/888885eb-569a-440f-9324-7cc49d8526ef)

**Comment by jendryk** [comment]
These are my addons that might do something with tooltips:
- HCRank
- Mendeleev
- MoPGearTooltips
- pfQuest + pfQuest-turtle
- pfUI-addonskinner
- TheoryCraft-Turtle
I will check them if I'll be able to login

**Comment by GryllsAddons** [comment]
Thank you, I've been able to reproduce this with SpamThrottle enabled but I can't see where it's changing the tooltip color in the SpamThrottle code. I've recoded the log tooltip to use an exact color instead which appears to resolve the issue. Please let me know if you have any further issues.

**Comment by jendryk** [comment]
Thanks! It works for the first part, but with SpamThrottle it still blacks out the "last words" part.

**Comment by GryllsAddons** [comment]
Thanks, should be fixed now. Out of interest does the black text happen to any other addons? still trying to work out why the default color doesn't work with spamthrottle.

**Comment by jendryk** [comment]
Didn't notice any other addon having black/unreadable font.
