### ISSUE TITLE
Addon doesn't save position of the toast message.

### ISSUE THREAD

**Issue by polyakovmyu** [GryllsAddons/HCDeaths#5]
How to reproduce the bug:
- Default pos in the center;
- Moving by ctrl + shift after "/hcd move" command;
- Reload interface/relaunch the client;
- Toast message in the center.

**Comment by GryllsAddons** [comment]
Thanks for raising this. The position is stored to the [layout cache](https://wowpedia.fandom.com/wiki/Layout-local.txt) which may require you to logout following moving the toast/log to save the position.

**Comment by polyakovmyu** [comment]
Log is okay - same place where it was before update.
But toast acts weird. I see that x axis is zero because i move toast to the left but in game toast in the centre. 
I think that addon saves values into layout cache but doesn't use them and uses default values instead.

**Comment by GryllsAddons** [comment]
Thanks this should now be fixed in the latest version.

**Comment by polyakovmyu** [comment]
Thanks. It works!
