### ISSUE TITLE
Needs update with patch 1.17

### ISSUE THREAD

**Issue by Mstuholla** [GryllsAddons/HCDeaths#6]
Alerts stop working after a couple messages.

**Comment by GryllsAddons** [comment]
Thanks for raising this. Recently TWoW had implemented a severe limit on the amount of times you can use the /who command. I will need to recode the addon to use a different method of gaining the information.

**Comment by GryllsAddons** [comment]
I've updated this to work around the /who limit by using friend info instead. Please let me know if you have any issues!
