### ISSUE TITLE
Issue found.

### ISSUE THREAD

**Issue by Mstuholla** [GryllsAddons/HCDeaths#7]
![Error Screen](https://github.com/GryllsAddons/HCDeaths/assets/136859583/b14c3ddd-7aa8-484f-9b34-63931a260418)

It worked the very first death, and then this error shows up every time.

Appreciate your work on such a niche addon.

**Comment by GryllsAddons** [comment]
ah good catch, just updated. {lease let me know if you encounter any further issues.

**Comment by Mstuholla** [comment]
Your new method seems to be working. 

Noticed a small bug. No sound plays for messages where players meet level milestones.

**Comment by GryllsAddons** [comment]
Thanks your right! this part was changed as we can't play the different race sounds anymore. The latest version will now play the firework sound for progress messages. I'll look for more sounds later and perhaps it can choose a random one!
